# DE3601
Important: Swapped from `ldap2` to `ldap1`, not the other way around

## Possible switch, still no connectivity
2021-08-21T03:30:24.187566+00:00,6,3,ewr-stor-q01-1,qfsd[263]: (task352514) [/fs_identity/ldap/lone_ldap_client] Error refreshing LDAP connection: ldap_connection_error: Unable to make connection to LDAP server.: [ unknown function at fs/identity/services/ldapper_client/adapter.rs:179 ]; Base LDAP config: {
    bind_uri=ldap://ldap2.schrodinger.com,
    bind_domain=,
    bind_netbios=,
    bind_account=,
    bind_password=******,
    default_base_dns=[ OU=people,DC=schrodinger,DC=com, OU=groups,DC=schrodinger,DC=com ],
    tls_config={ use_plaintext=true, ca_cert= },
    kdc_address=,
    default_kdc_port=88,
    default_ldap_port=0
}
2021-08-21T03:30:24.188165+00:00,6,3,ewr-stor-q01-1,qfsd[263]: (task352514) [/fs_identity/ldap/lone_ldap_client] Error refreshing LDAP connection: ldap_connection_error: Unable to make connection to LDAP server.: [ unknown function at fs/identity/services/ldapper_client/adapter.rs:179 ]; Base LDAP config: {
    bind_uri=ldap://ldap1.schrodinger.com,
    bind_domain=,
    bind_netbios=,
    bind_account=,
    bind_password=******,
    default_base_dns=[ OU=people,DC=schrodinger,DC=com, OU=groups,DC=schrodinger,DC=com ],
    tls_config={ use_plaintext=true, ca_cert= },
    kdc_address=,
    default_kdc_port=88,
    default_ldap_port=0
}
